version: '3.7'

services:
    nsqd:
        image: nsqio/nsq:v${NSQ_VERSION}
        labels:
            ru.grachevko.dhu: 'nsqd'
        command: >-
            nsqd
            --log-level debug
            --lookupd-tcp-address nsqlookupd0:4160
            --lookupd-tcp-address nsqlookupd1:4160
            --lookupd-tcp-address nsqlookupd2:4160

    nsqlookupd0:
        image: nsqio/nsq:v${NSQ_VERSION}
        labels:
            ru.grachevko.dhu: 'nsqlookupd0'
        command: /nsqlookupd -log-level debug

    nsqlookupd1:
        image: nsqio/nsq:v${NSQ_VERSION}
        labels:
            ru.grachevko.dhu: 'nsqlookupd1'
        command: /nsqlookupd -log-level debug

    nsqlookupd2:
        image: nsqio/nsq:v${NSQ_VERSION}
        labels:
            ru.grachevko.dhu: 'nsqlookupd2'
        command: /nsqlookupd -log-level debug

    nsqadmin:
        image: nsqio/nsq:v${NSQ_VERSION}
        labels:
            ru.grachevko.dhu: 'nsqadmin'
        command:
            - nsqadmin
            - --http-address=0.0.0.0:4171
            - --lookupd-http-address=nsqlookupd0:4161
            - --lookupd-http-address=nsqlookupd1:4161
            - --lookupd-http-address=nsqlookupd2:4161
        depends_on:
            - nsqlookupd0
            - nsqlookupd1
            - nsqlookupd2

    tail:
        image: nsqio/nsq:v${NSQ_VERSION}
        command: >-
            nsq_tail
            --channel nsq_tail
            --topic local
            --lookupd-http-address nsqlookupd1:4161
        depends_on:
            - nsqd
            - nsqlookupd1
